### ISSUE TITLE
分享之前遇到过的Hadoop Yarn REST API未授权漏洞

### ISSUE THREAD

**Issue by codeyung** [MRdoulestar/whatMiner#4]
贴个地址吧。https://www.freebuf.com/vuls/173638.html
我已经把我服务器还原了、升级了hadoop把hdfs等端口对外限制了
只有内网和我本地ip访问的了；暂时没事了。

**Comment by MRdoulestar** [comment]
> 贴个地址吧。https://www.freebuf.com/vuls/173638.html
> 我已经把我服务器还原了、升级了hadoop把hdfs等端口对外限制了
> 只有内网和我本地ip访问的了；暂时没事了。

感谢分享！
